services:
  redis:
    image: redis:6.2.13
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --requirepass iot.2020
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    environment:
      - REDIS_PASSWORD=iot.2020
    volumes:
      - ./data:/data  # 映射 Redis 数据目录到本地

