spring:
  datasource:
    url: jdbc:mysql://localhost:3306/t_parking?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: v7L9pX2qR5sK3mN8bY4cZ6wA1dE0fG2h
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml