server:
  port: 10000
  servlet:
    context-path: /api

spring:
  profiles:
    active: log,mysql,mybatis,redis
  application:
    name: cloud-application-user












cyyaw:
  mqtt:
    topics:
      - aaaaaaa
      - cxccccc
    broker:
      - url: tcp://127.0.0.1:1883
        username: admin
        password: 123456
        clientId: sssddd

























